// <auto-generated />
using FirstMVC.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstMVC.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstMVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasCheckConstraint("CK_Email", "[Email] LIKE '%@%.%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.dupont@email.com",
                            FirstName = "Alice",
                            LastName = "Dupont",
                            Password = "Jt8L$ndm&kFq24cS"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.martin@email.com",
                            FirstName = "Bob",
                            LastName = "Martin",
                            Password = "5Gh#zBvKw3PxYrE"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie.nguyen@email.com",
                            FirstName = "Charlie",
                            LastName = "Nguyen",
                            Password = "fT7#eRm2QxLz9Dy$"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.lee@email.com",
                            FirstName = "David",
                            LastName = "Lee",
                            Password = "V6b$UwPcNz @hM8xK"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emma.garcia@email.com",
                            FirstName = "Emma",
                            LastName = "Garcia",
                            Password = "aH5%kXjL9$qBm2W"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank.chen@email.com",
                            FirstName = "Frank",
                            LastName = "Chen",
                            Password = "qJ9@fM8cWu5$xLrE"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace.wong@email.com",
                            FirstName = "Grace",
                            LastName = "Wong",
                            Password = "7Km&zRb#vGy2hNj"
                        },
                        new
                        {
                            Id = 8,
                            Email = "henry.zhang@email.com",
                            FirstName = "Henry",
                            LastName = "Zhang",
                            Password = "T4c#nSv@wGj2RkF"
                        },
                        new
                        {
                            Id = 9,
                            Email = "isabella.lopez@email.com",
                            FirstName = "Isabella",
                            LastName = "Lopez",
                            Password = "H8f$kL3q#sVp9Xy"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jack.kim@email.com",
                            FirstName = "Jack",
                            LastName = "Kim",
                            Password = "3ZgY*6tLx#pVfDhN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
